### PR TITLE
build-sys: make pedantic revive the default

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — COMMENTED** [review]
I wonder if we are really prepared to remove the non-pedantic option completely.

**Comment by amery** [comment]
> I wonder if we are really prepared to remove the non-pedantic option completely.

How I see it is: Today's codebase satisfies revive-pedantic.toml, that can change if we accept weaker rules. enforcing pedantic revive on projects that currently satisfy the pedantic rules prevent weaker code from being accidentally committed

**Comment by amery** [comment]
`slog` and `gossipcache` currently pass the `make PEDANTIC=1` test, so I don't see a reason to justify allowing those projects to be weakened again

**Review by karasz — APPROVED** [review]
LGTM now is a better time than later to enforce pedantic

**Comment by amery** [comment]
`v0.4.3` tagged

**Pull request merged**
