### PR TITLE
Add LICENCE file to submodules

### PR DESCRIPTION
**Pull request by amery**
and text amended as slog began in 2023

### CODE REVIEW

**Comment by amery** [comment]
attempting to get https://pkg.go.dev/github.com/darvaza-proxy/slog/zerolog and the others to work

**Comment by amery** [comment]
changed to symlinks to make clear they are all the same

**Review by karasz — CHANGES_REQUESTED** [review]
After adding zap please revise this to include it.

**Review by karasz — APPROVED** [review]
LGTM

**Pull request merged**
