### PR TITLE
add Wrap() and Wrapf() helpers

### PR DESCRIPTION
**Pull request by amery**
to save us from directly depending on github.com/pkg/errors

### CODE REVIEW

**Review by karasz — APPROVED** [review]
LGTM. albeit in the Error() function the msg is possibly misleading, you are using the same string to name two different strings.

**Comment by amery** [comment]
@karasz I don't mind dropping `slog.Errorf()` if you find it confusing with regard to `log.Error().Print(...)`
`fmt.Errorf()` is already perfect. `Wrap`/`Wrapf` is where things diverge and importing github.com/pkg/errors pollutes go.sum beyond reason

**Comment by amery** [comment]
or you mean renaming `slog.Error` to `slog.LevelError` (etc)?

**Comment by amery** [comment]
@karasz Errorf() discarded

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
v0.4.0 tagged

**Pull request merged**
