### PR TITLE
filtered: add logger that will filter entries

### PR DESCRIPTION
**Pull request by amery**
add logger that will restrict entries to a given level and
it's able to modify fields programmatically

### CODE REVIEW

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
@karasz branch rebased against the current `main`. I was thinking about an alternative to `FieldFilter` that would allow transforming one field into many, extracting data from an `http.Request` object for example.

```go
FieldOverride(slog.Logger, key string, value any)
FieldsOverride(slog.Logger, fields map[string]any)
```

**Comment by amery** [comment]
`MessageFilter` option added on an additional commit

**Comment by amery** [comment]
and now another commit to add the field overriders

**Comment by karasz** [comment]
Do we really need two functions? `FieldOverride` and `FieldsOverride`, a map is allowed to contain only one element.... albeit I understand the aggravation of being forced to create a map instead of passing strings around. I am undecided on this :-/

P.S. If you do not re-request a review my previous "Approve" still applies.

**Comment by amery** [comment]
> Do we really need two functions? `FieldOverride` and `FieldsOverride`, a map is allowed to contain only one element.... albeit I understand the aggravation of being forced to create a map instead of passing strings around. I am undecided on this :-/

having FieldsOverride was added mostly for symmetry WithField/WithFields, FieldOverride/FieldsOverride.
the change mentioned above would try to use FieldOverride if FieldsOverride isn't defined and so saving the user from being forced to implement both

**Review by karasz — APPROVED** [review]
might prove useful

**Pull request merged**
