### PR TITLE
discard: fixed Enabled() handling of the uninitialized logger

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by amery** [comment]
it still needs to be found why the Print()'s call to log.Output panics

**Review by karasz — COMMENTED** [review]
The function does what it says in the comment, so it is ok, but I am puzzled about why `Enabled` means only log `Fatal`.....

**Review by karasz — APPROVED** [review]
now that I realized that this is `discard`, LGTM

**Comment by amery** [comment]
> The function does what it says in the comment, so it is ok, but I am puzzled about why `Enabled` means only log `Fatal`.....

this was actually wrong. `discard` is enabled for `slog.Fatal` **AND** `slog.Panic` levels after reviewing `Logger.print`. comment updated too.

**Review by karasz — APPROVED** [review]
ok

**Comment by amery** [comment]
`darvaza.org/slog/handlers/discard@v0.4.8` tagged

**Pull request merged**
